# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchEngineUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1658, 791)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(199, 234, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 100))
        self.headerFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.headerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.headerFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.header = QtWidgets.QLabel(self.headerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(30)
        self.header.setFont(font)
        self.header.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(82, 122, 175);\n"
"border-bottom-style: solid;\n"
"border-bottom-width: 2px;\n"
"border-bottom-color: rgb(82, 122, 175);")
        self.header.setTextFormat(QtCore.Qt.RichText)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout_4.addWidget(self.header)
        self.verticalLayout.addWidget(self.headerFrame)
        self.seachBoxW = QtWidgets.QWidget(self.centralwidget)
        self.seachBoxW.setObjectName("seachBoxW")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.seachBoxW)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchBoxWI = QtWidgets.QWidget(self.seachBoxW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBoxWI.sizePolicy().hasHeightForWidth())
        self.searchBoxWI.setSizePolicy(sizePolicy)
        self.searchBoxWI.setMinimumSize(QtCore.QSize(0, 50))
        self.searchBoxWI.setMaximumSize(QtCore.QSize(16777215, 60))
        self.searchBoxWI.setStyleSheet("border-width: 5px;\n"
"border-radius: 5px;\n"
"")
        self.searchBoxWI.setObjectName("searchBoxWI")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.searchBoxWI)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchBox = QtWidgets.QLineEdit(self.searchBoxWI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.searchBox.sizePolicy().hasHeightForWidth())
        self.searchBox.setSizePolicy(sizePolicy)
        self.searchBox.setMinimumSize(QtCore.QSize(0, 50))
        self.searchBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.searchBox.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.searchBox.setFont(font)
        self.searchBox.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.searchBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px dashed rgb(82, 122, 175);\n"
"border-radius: 5px;\n"
"padding: 5px;")
        self.searchBox.setAlignment(QtCore.Qt.AlignCenter)
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout_2.addWidget(self.searchBox)
        self.verticalLayout_2.addWidget(self.searchBoxWI)
        self.responseTimeW = QtWidgets.QWidget(self.seachBoxW)
        self.responseTimeW.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.responseTimeW.setFont(font)
        self.responseTimeW.setObjectName("responseTimeW")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.responseTimeW)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.responseTimeW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.suggestionBtn = QtWidgets.QPushButton(self.responseTimeW)
        self.suggestionBtn.setStyleSheet("font-family: georgia;\n"
"font-size: 12pt;\n"
"font-style: italic;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(82, 122, 175);")
        self.suggestionBtn.setText("")
        self.suggestionBtn.setObjectName("suggestionBtn")
        self.horizontalLayout_5.addWidget(self.suggestionBtn, 0, QtCore.Qt.AlignLeft)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.responseTimeW)
        self.searchResult = QtWidgets.QLabel(self.seachBoxW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchResult.sizePolicy().hasHeightForWidth())
        self.searchResult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.searchResult.setFont(font)
        self.searchResult.setText("")
        self.searchResult.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.searchResult.setObjectName("searchResult")
        self.verticalLayout_2.addWidget(self.searchResult)
        self.verticalLayout.addWidget(self.seachBoxW)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(500, 0, 500, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMaximumSize(QtCore.QSize(200, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn1 = QtWidgets.QPushButton(self.frame)
        self.btn1.setMaximumSize(QtCore.QSize(30, 30))
        self.btn1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn1.setStyleSheet("font-size: 18pt;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(82, 122, 175);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(82, 122, 175);")
        self.btn1.setObjectName("btn1")
        self.horizontalLayout_4.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.frame)
        self.btn2.setMaximumSize(QtCore.QSize(30, 30))
        self.btn2.setStyleSheet("font-size: 18pt;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(82, 122, 175);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(82, 122, 175);")
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_4.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.frame)
        self.btn3.setMaximumSize(QtCore.QSize(30, 30))
        self.btn3.setStyleSheet("font-size: 18pt;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(82, 122, 175);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(82, 122, 175);")
        self.btn3.setObjectName("btn3")
        self.horizontalLayout_4.addWidget(self.btn3)
        self.btn4 = QtWidgets.QPushButton(self.frame)
        self.btn4.setMaximumSize(QtCore.QSize(30, 30))
        self.btn4.setStyleSheet("font-size: 18pt;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(82, 122, 175);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(82, 122, 175);")
        self.btn4.setObjectName("btn4")
        self.horizontalLayout_4.addWidget(self.btn4)
        self.btn5 = QtWidgets.QPushButton(self.frame)
        self.btn5.setMaximumSize(QtCore.QSize(30, 30))
        self.btn5.setStyleSheet("font-size: 18pt;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: rgb(82, 122, 175);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(82, 122, 175);")
        self.btn5.setObjectName("btn5")
        self.horizontalLayout_4.addWidget(self.btn5)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout.addWidget(self.widget)
        self.buttonW = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonW.sizePolicy().hasHeightForWidth())
        self.buttonW.setSizePolicy(sizePolicy)
        self.buttonW.setMaximumSize(QtCore.QSize(16777215, 100))
        self.buttonW.setObjectName("buttonW")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonW)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchBtn = QtWidgets.QPushButton(self.buttonW)
        self.searchBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBtn.sizePolicy().hasHeightForWidth())
        self.searchBtn.setSizePolicy(sizePolicy)
        self.searchBtn.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("georgia")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.searchBtn.setFont(font)
        self.searchBtn.setStyleSheet("font-family: georgia;\n"
"font-size: 28pt;\n"
"font-style: italic;\n"
"font-weight: bold;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(82, 122, 175);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(82, 122, 175);")
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout.addWidget(self.searchBtn)
        self.verticalLayout.addWidget(self.buttonW)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">UCI Information &amp; Computer Science Search Engine</span></p></body></html>"))
        self.searchBox.setPlaceholderText(_translate("MainWindow", "Type here to Search..."))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Response Time: ____</span></p></body></html>"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
